apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  part-of: k8s-anotherclass
  component: backend-server
  name: api-tester
  instance: api-tester-2223
  managed-by: kustomize
resources:
  - configmap-properties.yaml
  - deployment.yaml
  - hpa.yaml
  - secret-postgresql.yaml
  - service.yaml