# Default values for api-tester.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: 1pro/api-tester
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""

podLabels: {}

service:
  type: NodePort
  port: 80
  nodePort:

resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

envFrom:
  configMapRef: api-tester-2222-properties

# Additional volumes on the output Deployment definition.
volumes:
  - name: secret-datasource
    secret:
      secretName: api-tester-2222-postgresql

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - name: secret-datasource
    mountPath: /usr/src/myapp/datasource

nodeSelector:
  kubernetes.io/hostname: k8s-master

configmap:
  data:
    properties:

secret:
  data:
    postgresql: